### ISSUE TITLE
1.10.2 - (Some?) BoP biomes generating empty.

### ISSUE THREAD

**Issue by HellishINC** [maruohon/paintedbiomes#5]
Some (I say some because I haven't tested all biomes as there are quite a few) BoP biomes are generating empty when using paintedbiomes. What I mean by empty, is that they have no trees, flowers, tall grass, sugarcane, etc. A few that I have tried are: [Snowy Forest](https://i.imgur.com/QgbAdKA.png), [Snowy Coniferous Forest](https://i.imgur.com/ZC7Dx6l.png), [Coniferous Forest](https://i.imgur.com/5GTw0BB.png), [Cold Desert](https://i.imgur.com/gnL9Tp2.png), Boreal Forest, [Tundra](https://i.imgur.com/RR89aoZ.png), [Wasteland](https://i.imgur.com/hJdLT9A.png) and [Volcanic Island](https://i.imgur.com/xoJfLxO.png). Links are their intended appearance.

![example](https://cloud.githubusercontent.com/assets/4485158/26295105/2e5ace9a-3e96-11e7-9312-98b78b07fad1.jpg)

In case you'd like to be easily test some of the listed biomes (I'm not sure which biomes are which as the colors are all very similar and the red hurts my eyes to look at). It's a small world I know, but I did so as to not upload a 10mB png.
![biomes](https://cloud.githubusercontent.com/assets/4485158/26295418/d27be6d4-3e97-11e7-9644-d8253c5b42be.png)
[Colors in case they different](https://gist.github.com/HellishINC/d0614c29e169704f59930d3c7546255d)

I also tried setting useGenLayer to true and overriding the chunkProviderType but I had the same results.

I should also mention that I also tried an older version of BoP but that too yielded the same end result.

**Comment by maruohon** [comment]
Do you have other mods installed that deal with biomes or terrain generation?

**Comment by maruohon** [comment]
Okay this seems to simply be an issue that BoP requires the WorldType to be BIOMESOP, or it doesn't seem to do any decoration.

So, for example:
* With default WorldType: http://i.imgur.com/GrqfwzN.png
* With BIOMESOP WorldType: http://i.imgur.com/gDHac48.png

**Comment by HellishINC** [comment]
Thank you for finding the solution!

**Comment by maruohon** [comment]
Hm, missed your edit because that doesn't send a notification...

That's not something that PB currently deals with. It could be done by overriding it from the WorldInfo. But I don't really see the benefit in doing that via PB instead of just selecting it normally when creating the world. Unless you mean it would only take effect on some areas? And that is not possible, because there is no way to know from where and for what purpose something is asking for the WorldType, it's a global thing and not tied to any location.
