### ISSUE TITLE
Biome configuration not being applied to world with DEFAULT generator

### ISSUE THREAD

**Issue by Sukasa** [maruohon/paintedbiomes#6]
Playing SSP 1.12.1, trying to test my configuration.  For some reason, my biomes.png map is not being applied.

I've placed it in the folder it's supposed to be in (and the log indicates that it's found), however it's just using a default biome provider and not my biome map.  There don't appear to be any errors

What have I done that's caused this to not work, and what can I do to fix it?

Log excerpt:
> [21:18:28] [Server thread/INFO] [paintedbiomes]: Wrapping the BiomeProvider (of type net.minecraft.world.biome.BiomeProvider) of dimension 0 with fi.dy.masa.paintedbiomes.world.BiomeProviderPaintedBiomes
> [21:18:28] [Server thread/INFO] [paintedbiomes]: Successfully read template image from 'D:\MultiMC\instances\1.12.1. PvP Pack\minecraft\saves\Biome Painter Test\paintedbiomes\templates\dim0\biomes.png' (dimensions: 3800x3800)

per-world config:
[paintedbiomes.cfg.txt](https://github.com/maruohon/paintedbiomes/files/1313042/paintedbiomes.cfg.txt)

Biome map:
![biomes](https://user-images.githubusercontent.com/1186656/30575748-c0ff5c5a-9cb7-11e7-8e29-e5c386f424e1.png)

Full mod list:
[Mods.txt](https://github.com/maruohon/paintedbiomes/files/1313056/Mods.txt)

**Comment by maruohon** [comment]
Hmm, I tried it using your template image and config, and it seems to be working. I had mostly just BoP and Painted Biomes installed while testing.

Some notes/questions:
* Since you said you are using per-world configs, did you create the `<worldname>/paintedbiomes/paintedbiomes.cfg` directory and config file before generating the world? Otherwise at least the spawn area obviously wouldn't have the options enabled yet. You can create the world save directory before generating the world, by simply naming it the same as you will name the world, although it doesn't allow many special character, they would get converted to underscores (you can easily test out how that works..). Another possibility is to just generate a "dummy" world first, save & exit to main menu, then remove everything except the `level.dat` file from the save directory of that world and add in the paintedbiomes directory, and then generate the world again.
* The config you posted is named `paintedbiomes.cfg.txt`. Is that the case also on your filesystem? It must be just `paintedbiomes.cfg`, ie. not the `.txt` extension. (I'd maybe recommend enabling the show file name extensions option in the file explorer.)
* Once the above is ok, do you get a log message like: `[14:38:36] [Server thread/INFO] [paintedbiomes]: Loading configuration from 'C:\Users\masa\Desktop\MultiMC5\instances\1.12.x mod test\minecraft\saves\TMP3\paintedbiomes\paintedbiomes.cfg'`?
* Note that since you are using BoP biomes, you need to be using the Biomes O' Plenty (BIOMESOP on server) WorldType, otherwise the BoP biomes won't get decorated at all.
* In your config, the unpainted and undefined area biomes are set wrong - they should not be the numerical ID anymore, but instead the registry name (this is a somewhat recent change). So in your case, since 24 seems to be Deep Ocean, they should be set to `minecraft:deep_ocean` (I can't remember whether or not they need double quotes around them in the Forge config format...)

**Comment by Sukasa** [comment]
Okay, thanks for pointing out the mismatch with the biome IDs, and in that config format no " is required in my experience.


And yes, it's named paintedbiomes.cfg in the filesystem.  Github won't allow an upload with that extension, hence the .txt added.  I'm pretty sure it's the correct file as it was auto-populated by PaintedBiomes when I created a blank file.

After I set up the world, I deleted all of the files in /region/ and reloaded it, to generate fresh.  I'll start playing with plugins, and see if I can narrow down which one is causing problems.

**Comment by Sukasa** [comment]
Looks like it's a mod conflict with Astral Sorcery.  Any time that mod is enabled, PaintedBiomes has no effect.

**Comment by maruohon** [comment]
Hmm, interesting. Have you tried enabling the `useGenLayer` option to see if that method works in this case? The consequence of using that is that any custom "normal" overworld dimensions would then also very likely get the same biome layout, because that event doesn't currently know the dimension ID or have a world reference so that it could be targeted to only specific dimensions...

**Comment by Sukasa** [comment]
I have not, but I will try it.

[I've created an issue on the AS issue page as well](https://github.com/HellFirePvP/AstralSorcery/issues/289)

**Comment by Sukasa** [comment]
setting useGenLayer=true works around the problem as well.

**Comment by maruohon** [comment]
I'm assuming this has been solved.
