### ISSUE TITLE
Crash with Forge server 1.12.2, Forge 14.23.1.2604

### ISSUE THREAD

**Issue by Bulldog83** [maruohon/paintedbiomes#7]
Crash-report: https://gist.github.com/Bulldog83/6eb581711b347f85af40951942146bd5

**Comment by maruohon** [comment]
This crash (and also another crash that happened on a dedicated server after this was fixed...) has now been fixed in the 0.5.4 version.

It seems that nobody else had tried to use the mod on a dedicated server on 1.12+ (or even before? so in quite a while...), or at least not bothered reporting the crash... So thank you for reporting this :)
